atom/symbols-view

lib/load-tags-handler.coffee
The README says .tags is supported - but that's incorrect. This PR fixes that.
=> Bugfix: .tags doesn't work as filename

lib/tag-generator.coffee
I guess it's because sometimes `ctags` produce too much warings in `stderr`, if we don't handle it, the process will be blocked.
=> Fix issue #87, symbols generator is blocked

menus/symbols-view.cson
Part of atom/settings-view#354
This removes Go to Declaration from mini editors' context menus - if this is a bit too far-reaching I can limit it to mini editors in panes without file paths, but the current behavior is confusing.
=> Remove Go to Declaration from mini editor context menu

lib/file-view.coffee, lib/symbols-view.coffee, package.json, spec/symbols-view-spec.coffee, styles/symbols-view.less
This adds match highlighting for symbols in the Symbols View:
(Thanks @philschatz for the implementation in fuzzy-finder!)
/cc @kevinsawicki
=> Add match highlighting for symbols

lib/file-view.coffee, lib/symbols-view.coffee, spec/symbols-view-spec.coffee
- only applies to FileView
- takes care of restoring initial editor state if view does not get confirmed
- fixes #19
=> Add support for quickly jumping to symbol positions for FileView

lib/ctags-config, lib/tag-generator.coffee
[Cap'n Proto](https://capnproto.org/language.html) is binary format RPC protocol, which has own schema language to support cross platform, cross language. 
I add simple support for Cap'n Proto schema language. It supports struct enum using const.
=> Add simple support for Cap'n Proto (capnp) schema language

spec/symbols-view-spec.coffee
Closes #128 
I have seen these specs failing a bunch of times on atom/atom, and they almost always seem false positives. This PR spies upon `SymbolsView::setLoading` instead of checking for `::loading` visibility: the problem with using `toBeVisible()` is that, whenever loading is faster than our test code, the assertion will get executed **after** loading has been already hidden, thus making the tests fail.
I'll give them a couple of spins on Travis to see whether or not this fixes it. If after 5 times it's always green, I'll go on and :ship: this.
=> More resilient spec

lib/ctags-config
This adds support for [ES2015 static class methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Static_methods) in JavaScript.
=> Add support for ES2015 static methods

lib/ctags-config
@atom/feedback ...any reason not to add these to the symbols-view? I've been writing a lot of babelized classes with async/await lately and this definitely makes my life better.
=> Add es7 async functions to ctags

lib/file-view.coffee, package.json, spec/symbols-view-spec.coffee
I want quick jump is optional.
Its not only because of issue I reported in #105.
Its because I don’t like frequent screen update.
Maybe there are other people like me.
=> Make quickJumpToSymbol optional

lib/tag-reader.coffee, package.json, spec/fixtures/ruby/file1.rb, spec/fixtures/ruby/tags, spec/symbols-view-spec.coffee
- Fixes jumping to `foo?`/`foo!` declarations when the current scope is an ERB template.
- **New feature:** enables selecting text such as `Foo::Bar` and jumping to that as a tag to look up. When there is no selection, falls back to word under cursor.
More details in commit messages.
=> Fix go-to-declaration for Ruby identifiers in some cases

lib/go-back-view.coffee, lib/symbols-view.coffee
Fixes the following bug:
* Create a new file, but don't save it.
* Use go-to-declaration to jump to the definition of the word under cursor.
* Use return-from-declaration to jump back.
Expected: the active text editor focus returns to unsaved file.
Actual: a new blank file tab gets opened.
=> Fix return-from-declaration when navigating to an unsaved file

lib/get-tags-file.coffee
I keep my tag files in .git/ subdirectory for all my projects which is handy -
no need to update `.gitignores` file for project I don't own.
=> Added support for tags in .git directory

lib/ctags-config
This allows function calls as default parameter values by loosening the regex to allow closing parentheses within a method parameter list. Can't think of how this would create false positives so we'll give this a try.
It also excludes `switch` and `with` flow control constructs from being matched as if they were methods.
=> Improve JS method regex in ctags config

lib/file-view.js, lib/get-tags-file.js, lib/go-back-view.js, lib/go-to-view.js, lib/load-tags-handler.js, lib/main.js, lib/project-view.js, lib/symbols-view.js, lib/tag-generator.js, lib/tag-reader.js, package.json, spec/async-spec-helpers.js, spec/symbols-view-spec.js
This pull request uses atom-select-list as a drop-in replacement for atom-space-pen-views. Feature-wise nothing should change, but this will help remove jQuery from Atom.
/cc: @ungb for 👀
=> Replace atom-space-pen-views with atom-select-list

spec/symbols-view-spec.js
The `TextBuffer.save` method is going to become async in atom/atom#14435; instead of doing a synchronous write, it will initiate an asynchronous write and return a promise when the write completes. This shouldn't affect the user-facing functionality of many packages; but several packages may have test failures.
This PR updates the two tests in `symbols-view` that broke due to this change, so that they work regardless of whether save is synchronous or asynchronous.
=> Wait for save to complete in tests

lib/ctags-config, lib/tag-generator.js
Added support for the modern ColdFusion and CFML language scripting constructs. I have also added support for BDD (Behavior Driven Development) constructs using the TestBox framework  for modern CFML script testing.
Symbols view for the ColdFusion/CFML language was non-existent, therefore I decided to do the pull request to support it.  CFML is very similar to Java and JavaScript and provides almost 90% compatibility in language constructs as a modern JVM language.  As you will see from the pull request, the changes are trivial.
The entire ColdFusion and CFML eco-system will now be able to use Atom for symbols lookup instead of relying on Sublime.
None that we can see.
None that we can see.
=> Added ColdFusion/CFML language support

lib/tag-generator.js
Refs: https://github.com/atom/atom/pull/14682.
This pull-request changes symbols-view to allow it to correctly detect the `ctags` binary when Atom is bundled with both snapshots and .asar archives. This entails detecting whether the file was snapshotted or not: if so, we need to use `resourcePath` to resolve the package root path, otherwise we can simply traverse the directory tree upward.
Once we know what the absolute path of the package is, we need to detect whether Atom used `.asar` archives or not. If so, we need to search for `ctags` in the `.unpacked` folder where non-source files are stored during the creation of the .asar archive.
/cc: @iolsen
=> Fix ctags executable path resolution to support .asar+snapshots in Atom

lib/ctags-config
We already support [Jasmine functions for CoffeeScript](https://github.com/atom/symbols-view/blob/7ea798df72249393db274ee25f9a541aea707c32/lib/ctags-config#L5-L16). With the changes in this pull request, we bring that same support to JavaScript.
Specifically, symbols-view will identify the following items as functions:
- `describe` blocks
- `it` blocks
- focused `it` blocks (e.g., `fit`, `ffit`, `fffit`, etc.)
- focused `describe` blocks (e.g., `fdescribe`, `ffdescribe`, `fffdescribe`, etc.)
- disabled `it` blocks (i.e., `xit`)
- disabled `describe` blocks (i.e., `xdescribe`)
We can try this out inside symbol-views very own specs. (So meta.) Let's start by editing [`spec/symbols-view-spec.js`](https://github.com/atom/symbols-view/blob/007de32abd369144c5b920c5aa51a4eff08a4284/spec/symbols-v …
=> Add support for top-level Jasmine functions in JavaScript

lib/symbols-view.js
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
Remove a double caret from a regex in `symbols-view.js`. To the best of my understanding, this just matches the start of the string twice, which is a no-op.
Cleanup.
None, unless this double caret holds some secret meaning I don't know about. 😉
=> Remove a redundant caret in the regex in symbols-view.js

lib/symbols-view.js, spec/fixtures/c/sample.c, spec/fixtures/c/tags, spec/symbols-view-spec.js
* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
Line numbers are emmited by ctags, by default, in some cases. This is true for C preprocessor macros, for example. So properly handle them.
The user can request not to emit them (The `--excmd` argument to ctags, and short forms of it) but it's best for Atom to handle this correctly since this is part of the [documented syntax of ctags](http://ctags.sourceforge.net/ctags.html#TAG%20FILE%20FORMAT).
Original by: @raphinesse (PR #187). This is an updated version of that PR to ES6 from CoffeeScript + Minor Changes. Hope you don't mind 😉.
symbols-view will …
=> If present, use tag line number instead of search pattern.

lib/file-view.js
This will prevent this package from providing its functionality to editors more than once in case they get added to the workspace, then removed from it and finally added back.
/cc: @nathansobo @jasonrudolph
=> Don't watch editors more than once if they're re-added to the workspace

lib/symbols-view.js
setCursorBufferPosition on L91 is thrashing scrollToBufferPosition on L90.
Passing autoscroll: false in the options for setCursorBufferPosition fixes
this.
Fixes #132
=> When scrolling to symbol, center it in the buffer
